FROM node:16-alpine
RUN apk  --no-cache --update add go git tzdata poppler poppler-utils poppler-data && \
    cp /usr/share/zoneinfo/Asia/Tokyo /etc/localtime && \
    apk del tzdata

WORKDIR /workspace/
VOLUME [ "front-node_modules:/workspace/front/node_modules" ]

RUN mkdir /workspace/front
COPY ./front/package.json ./front
RUN yarn --cwd /workspace/front

ENTRYPOINT [ "yarn","--cwd","/workspace/front", "start" ]