# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: sail CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18]
    defaults:
      run:
        working-directory: ./front
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
        cache-dependency-path: ./front/yarn.lock  
    - name: yarn build
      run: |
        yarn --cwd ./front
        yarn --cwd ./front build
        cp ./front/dist/* ./server/static/ -R
      env:
        HTML: index.html
    - uses: actions/setup-go@v3
    - run: go build -ldflags="-s -w" -trimpath -o ../dist/
      working-directory: server
      env:
        GOOS: linux
        GOARCH: amd64
