name: ci

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18]
    steps:
      - uses: actions/checkout@v3
      # build node.js
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
          cache-dependency-path: ./front/yarn.lock  
      - name: yarn build
        run: |
          yarn --cwd ./front
          yarn --cwd ./front build
          cp ./front/dist/* ./cmd/sail/static/ -R
        env:
          HTML: index.html

      - uses: actions/setup-go@v5
        with:
          go-version: "1.21.x"
      # release
      - uses: goreleaser/goreleaser-action@v5
        with:
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload assets
        uses: actions/upload-artifact@v3
        with:
          name: sail
          path: dist/*
